$mainMod = Super 

$term = kitty
$file = dolphin
$browser = firefox

bind = $mainMod, W, killactive
bind = $mainMod, M, exec, hyprlock
bind = $mainMod, G, togglegroup,
bind = $mainMod, F, fullscreen, 1
bind = SUPER, period, exec, ~/.config/scripts/emoji.sh

bind = $mainMod, Q, exec, $term
bind = $mainMod, E, exec, $file
bind = $mainMod, B, exec, $browser

bind = $mainMod+Ctrl, Return, exec, pkill -x rofi || ~/.config/scripts/rofilaunch.sh 
bind = $mainMod+Shift, S, exec, ~/.config/scripts/screenshot.sh

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u
bind = $mainMod, l, movefocus, r


binde = $mainMod+Shift, L, resizeactive, 30 0
binde = $mainMod+Shift, h, resizeactive, -30 0
binde = $mainMod+Shift, k, resizeactive, 0 -30
binde = $mainMod+Shift, j, resizeactive, 0 30

bind = $mainMod+Shift, 1, movetoworkspace, 1
bind = $mainMod+Shift, 2, movetoworkspace, 2
bind = $mainMod+Shift, 3, movetoworkspace, 3
bind = $mainMod+Shift, 4, movetoworkspace, 4
bind = $mainMod+Shift, 5, movetoworkspace, 5
bind = $mainMod+Shift, 6, movetoworkspace, 6
bind = $mainMod+Shift, 7, movetoworkspace, 7
bind = $mainMod+Shift, 8, movetoworkspace, 8
bind = $mainMod+Shift, 9, movetoworkspace, 9
bind = $mainMod+Shift, 0, movetoworkspace, 10


bindel = , XF86AudioRaiseVolume, exec, ~/.config/scripts/volume-notify.sh up
bindel = , XF86AudioLowerVolume, exec, ~/.config/scripts/volume-notify.sh down
bindl  = , XF86AudioMute,        exec, ~/.config/scripts/volume-notify.sh mute
